### ISSUE TITLE
怎么TIMERA_HwTriggerInit的TMRA3 BUG还没修复,反馈了半年,

### ISSUE THREAD

**Issue by ls120662425** [hdscmcu/hc32f460#1]
怎么TIMERA_HwTriggerInit / TIMERA_HwClearConfig 的TMRA3 BUG还没修复,反馈了半年,赶紧改了, 是PWM3 不是单元3
if (M4_TMRA3 == TIMERAx) 这里
如果觉得没问题可以和我辩论

**Comment by JamieTx** [comment]
> 怎么TIMERA_HwTriggerInit / TIMERA_HwClearConfig 的TMRA3 BUG还没修复,反馈了半年,赶紧改了, 是PWM3 不是单元3
> if (M4_TMRA3 == TIMERAx) 这里
> 如果觉得没问题可以和我辩论
